accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    # path('', views.indexView, name="home"),
    # path('dashboard/', views.dashboardView, name="dashboard"),
    path('login/', views.user_login, name="login_url"),
    path('register/',views.registerView, name="register_url"),
    path('logout/',views.logout_view, name="logout"),
    path('signout/', views.user_logout, name = "signout"),
]

app6/urls.py
from django.urls import path
from . import views

app_name = 'app6'

urlpatterns = [
    path('', views.index, name='index'),
    path('story/', views.story, name='story'),
    path('search/', views.search, name='search'),

]

project6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app6.urls')),
    path('accounts/', include('accounts.urls')),
    # path('admin/', include('special.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

app6/models.py
from django.db import models

# Create your models here.
class Status_Form(models.Model):
	status = models.CharField(max_length=300)
	date = models.DateTimeField(auto_now_add=True, editable=False)

app6/forms.py
from django import forms

class Form(forms.Form):
	error_messages = {
		'required': 'This field is required',
	}
	attrs = {
		'class': 'status-form-textarea',
		'type': 'text',
	}
    
	status = forms.CharField(label='Status', required=True, max_length=300, widget=forms.TextInput(attrs=attrs))

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.http.response import HttpResponse

# Create your views here.

response = {}

# def indexView(request):
#     return render(request, 'accountsIndex.html')

# @login_required
# def dashboardView(request):
#     return redirect('app6:index')

def registerView(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login_url')
    else:
        form = UserCreationForm()

    return render(request, 'registration/register.html', {'form' : form })

def user_login(request):
    response['username'] = "username"
    if request.method == "POST":
         username = request.POST['username']
         password = request.POST['password']
         user = authenticate(request, username=username, password=password)
         if user is not None:
            login(request, user)
            request.session['username'] = username
            response['username'] = request.session['username']
            return redirect('app6:index')
         else:
            return HttpResponse("Username and Password didn't match")
    else:
        return render(request, 'registration/login.html',response)

def logout_view(request):
    return render(request, 'registration/logout.html')


def user_logout(request):
    request.session.flush()
    logout(request)
    return redirect('app6:index')


    

app6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import Form
from .models import Status_Form
from django.db import IntegrityError

# Create your views here.
response = {}

def index(request):
	result = Status_Form.objects.all()
	if request.method == 'POST':
		form = Form(request.POST)
		if form.is_valid():
			status = request.POST['status']
			create_stat = Status_Form.objects.create(status=status) 
			return render(request, 'index.html', {'form' : form, 'status':result})
	else:
		form = Form()
	return render(request, 'index.html', {'form' : form, 'status':result})

def story(request):
	return render(request, 'story.html')

def search(request):
	return render(request, 'search.html')

accounts/templates/navbar/head2.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">

accounts/templates/navbar/navbar2.html
<div class="container">
        <nav class="navbar  navbar-expand-lg navbar-light ">
            <!-- <a class="navbar-brand" href="{% url 'special:special' %}">kukuh.</a> -->
            <a class="navbar-brand" href="#">kukuh.</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-lg-auto">
                   
                    <li class="nav-item">
                        <a class="{% if current_nav == 'index' %}nav-link active{% endif %} nav-link" href="{% url 'app6:index' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="{% if current_nav == 'story' %}nav-link active{% endif %} nav-link" href="{% url 'app6:story' %}">Story</a>
                    </li>
                    <li class="nav-item">
                        <a class="{% if current_nav == 'search' %}nav-link active{% endif %} nav-link" href="{% url 'app6:search' %}">Search</a>
                    </li>
                    <li class="nav-item">
                        <a class="{% if current_nav == 'login' %}nav-link active{% endif %} nav-link" href="{% url 'accounts:logout' %}" id="logout">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="{% if current_nav == 'login' %}nav-link active{% endif %} nav-link" href="{% url 'accounts:login_url' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                
            </div>
        </nav>
    </div>

app6/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        {% include 'navbar/head.html' %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <title>Story6_Kukuh</title>
    </head>
    <body>
        <header>
            {% block navbar %}
            {% with current_nav='index' %}
            {% include 'navbar/navbar.html' %}
            
            {% endwith %}
            {% endblock navbar %}
        </header>
        <section class="banner">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        {% if user.is_authenticated %}
                        <h2>Hello {{ user.username }}, How are you?</h2>
                        {% else %}
                        <h2>Hello, How are you?</h2>
                        {% endif %}
                        {% for i in status %}
                        <p>{{ i.status }} <br>
                            {{ i.date }}
                        </p>
                        {% endfor %}
                    </div>
                    <div class="col-sm-6">
                        <form class="box" action="" method="post">
                            {% csrf_token %}
                            <h1>status</h1>
                            {% for status in form %}
                            <div class="form-group">
                                {{ status }}
                            </div>
                            {% endfor %}
                            <button type="submit" id = "submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

app6/templates/navbar/head.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">

app6/templates/navbar/navbar.html
<div class="container">
    <nav class="navbar  navbar-expand-lg navbar-light ">
        <!-- <a class="navbar-brand" href="{% url 'special:special' %}">kukuh.</a> -->
        <a class="navbar-brand" href="#">kukuh.</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-lg-auto">
               
                <li class="nav-item">
                    <a class="{% if current_nav == 'index' %}nav-link active{% endif %} nav-link" href="{% url 'app6:index' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="{% if current_nav == 'story' %}nav-link active{% endif %} nav-link" href="{% url 'app6:story' %}">Story</a>
                </li>
                <li class="nav-item">
                    <a class="{% if current_nav == 'search' %}nav-link active{% endif %} nav-link" href="{% url 'app6:search' %}">Search</a>
                </li>
                <li class="nav-item">
                    <a class="{% if current_nav == 'login' %}nav-link active{% endif %} nav-link" href="{% url 'accounts:logout' %}" id="logout">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="{% if current_nav == 'login' %}nav-link active{% endif %} nav-link" href="{% url 'accounts:login_url' %}">Login</a>
                </li>
                {% endif %}
            </ul>
            
        </div>
    </nav>
</div>

app6/templates/search.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        {% include 'navbar/head.html' %}
        <link rel="stylesheet" href="{% static 'css/search.css' %}">
        <title>Story6_Kukuh</title>
    </head>
<body>
    <header>
        {% block navbar %}
        {% with current_nav='search' %}
        {% include 'navbar/navbar.html' %}
        
        {% endwith %}
        {% endblock navbar %}
    </header>
    <div class="all" id="demo">
        <div class="newsletter">
            <h1>
                Book
                <span>Catalogue</span>
            </h1>
            <p>Search for your favorite book here!</p>
            <div class="txtb">
                <input type="search" id="search" placeholder="Type to Search">
                <button type="button" id="button" ><i class="fas fa-search"></i></button>
            </div>
            <table class="table"></table>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.11.3.js"></script>
    <script src="{% static 'js/script.js' static %}"></script>
        

    
</body>
</html>

app6/templates/story.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    {% include 'navbar/head.html' %}
    <link rel="stylesheet" href="{% static 'css/story.css' %}">
    <title>Story</title>
</head>
<body>
    <header>
        {% block navbar %}
        {% with current_nav='story' %}
        {% include 'navbar/navbar.html' %}
        
        {% endwith %}
        {% endblock navbar %}
    </header>
    
        <section class="banner">
            <div id="accordion">
                <h3 class="accordion__button">Activities</h3>
                <div class="content">
                    <p>Staff at Sports Departement in BEM Fasilkom UI</p>
                    <p>Students at Fasilkom UI</p>
                </div>
                <h3 class="accordion__button">Organization and Experiences</h3>
                <div class="content">
                    <p>Sport Departement Staff BEM Fasilkom UI (2019)</p>
                    <p>Event Staff Computer Science League Fasilkom UI (2019)</p>
                    <p>Decoration and Costume Staff COMPFEST Fasilkom UI (2019)</p>
                    <p>Documentation and Creative Staff SIWAK-NG Fasilkom UI (2019)</p>
                </div>
                <h3 class="accordion__button">Achievements</h3>
                <div class="content">
                    <p>No Achievements Yet</p>
                </div>
            </div>
            <div>
                <ul id="theme1">
                    <li id="theme2">
                        <span>Dark</span>
                        <span>Light</span>
                    </li>
                </ul>
            </div>
        </section>
        <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $('#theme1').click(function(){
                    $('#theme1').toggleClass('active')
                    $('body').toggleClass('dark')
                    $("h3").toggleClass('dark')
                })
            })    
        </script>
        <script>
            $( function() {
              $( "#accordion" ).accordion({
                collapsible: true
              });
            } );
        </script>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    
</body>
</html>